/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import Operations.Validations;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import model.To.LoginInfoTO;
import model.dao.LoginInfoDAO;
import screens.adminscreen.AdminMainScreen;
import screens.userscreen.UserMainScreen;

/**
 *
 * @author Rahul khurana
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfUserName = new javax.swing.JTextField();
        jpfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setText("Enter User Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 293, 52);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("Enter User Password :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(13, 130, 280, 55);

        jtfUserName.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jPanel1.add(jtfUserName);
        jtfUserName.setBounds(330, 40, 340, 52);

        jpfPassword.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jPanel1.add(jpfPassword);
        jpfPassword.setBounds(330, 130, 340, 55);

        btnLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnLogin.setText("Click To Login...");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(140, 230, 463, 81);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/clr.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 680, 350);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 697, 394);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String uname = jtfUserName.getText();
        String pass = new String(jpfPassword.getPassword());
        String message = "";
        if (Validations.isEmpty(uname) || Validations.isEmpty(pass)) {
            message = "Please Enter some value";
        } else {
            LoginInfoDAO action = new LoginInfoDAO();
            LoginInfoTO record = action.getRecord(uname);
            if (record != null) {
                if (record.getPassword().equals(pass)) {
                    if (record.getRolename().equals("admin")) {
                        AdminMainScreen ams = new AdminMainScreen();
                        ams.setVisible(true);
                        if (record.getLastlogin() == null) {
                            message = "Welcome First time!!!";
                        } else {
                            message = "Your Last visit: " + record.getLastlogin();
                        }
                        record.setLastlogin(new Timestamp(System.currentTimeMillis()));
                        action.updateRecord(record);
                        dispose();

                    } else if (record.getRolename().equals("user")) {
                        UserMainScreen ums = new UserMainScreen(uname);
                        ums.setVisible(true);
                        if (record.getLastlogin() == null) {
                            message = "Welcome First time!!!";
                        } else {
                            message = "Your Last Visit : " + record.getLastlogin();
                        }
                        record.setLastlogin(new Timestamp(System.currentTimeMillis()));
                        action.updateRecord(record);
                        dispose();
                    } else {
                        message = "Insufficient Privileges Contact To Administrator";
                    }
                } else {
                    message = "Invalid User Name and Password";
                }
            } else {
                message = "Invalid User Name and Password";
            }
        }
        JOptionPane.showMessageDialog(this, message);

    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfUserName;
    // End of variables declaration//GEN-END:variables
}
