/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.adminscreen;

import Operations.CommonOperations;
import Operations.Validations;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;
import javax.swing.JOptionPane;
import model.To.BrandInfoTO;
import model.To.CategoryInfoTO;
import model.To.ClothInfoTO;
import model.To.ClothStockTO;
import model.To.SubCategoryTO;
import model.dao.ClothInfoDAO;
import model.dao.ClothStockDAO;
import model.dao.SubCategoryDAO;
import mondrian.spi.Dialect;

/**
 *
 * @author Rahul khurana
 */
public class AddClothStock extends javax.swing.JInternalFrame {

    private int stockid;

    public AddClothStock() {
        initComponents();
        jcbClothId.removeAllItems();
        jcbClothId.addItem("Choose Any ClothId");
        List<ClothInfoTO> clothId = new ClothInfoDAO().getAllRecord();
        if (clothId != null && clothId.size() > 0) {
            for (ClothInfoTO cit : clothId) {
                jcbClothId.addItem(cit);
            }
            lblPriceNameError.setVisible(false);
            lblQtyNameError.setVisible(false);
        }
    }

    public AddClothStock(int stockid) {
        this();
        ClothStockTO record = new ClothStockDAO().getRecord(stockid);
        if (record != null) {
            this.stockid = stockid;
            setTitle("Update ClothStock");
            btnAssigned.setText("Update ClothStock Details");

            for (int i = 1; i < jcbClothId.getItemCount(); i++) {
                ClothInfoTO cit = (ClothInfoTO) jcbClothId.getItemAt(i);
                if (cit.getClothid() == (record.getClothid())) {
                    jcbClothId.setSelectedIndex(i);
                    break;
                }
            }
            jtfPrice.setText(String.valueOf(record.getPrice()));
            jtfQty.setText(String.valueOf(record.getQty()));
            fdpStockDate.setDate(record.getStockdate());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jcbClothId = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfQty = new javax.swing.JTextField();
        fdpStockDate = new controls.FutureDatePanel();
        btnAssigned = new javax.swing.JButton();
        lblPriceNameError = new javax.swing.JLabel();
        lblQtyNameError = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Cloth Stock");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setText("Choose Cloth Id :-");

        jcbClothId.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jcbClothId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbClothId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClothIdActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel5.setText("Choose Stock Date :-");

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel6.setText("Enter Price :-");

        jtfPrice.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jtfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPriceActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel7.setText("Enter Quantity :-");

        jtfQty.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jtfQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfQtyActionPerformed(evt);
            }
        });

        btnAssigned.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnAssigned.setText("Assign Cloth Stock");
        btnAssigned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignedActionPerformed(evt);
            }
        });

        lblPriceNameError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Error.png"))); // NOI18N

        lblQtyNameError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Error.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblQtyNameError))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fdpStockDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jtfQty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                                    .addComponent(jcbClothId, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPriceNameError))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbClothId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblQtyNameError)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblPriceNameError))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfQty, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fdpStockDate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbClothIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClothIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbClothIdActionPerformed

    private void jtfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPriceActionPerformed

    private void jtfQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfQtyActionPerformed

    private void btnAssignedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignedActionPerformed
        String message = "";
        boolean allvalid = true;
        if (jcbClothId.getSelectedIndex() == 0) {
            message += "Please Chosse Any Category\n\n ";
            allvalid = false;
        }
        String PriceName = jtfPrice.getText().trim();
        if (Validations.isEmpty(PriceName)) {
            message += "Please Enter Some Value In Price Box\n\n";
            lblPriceNameError.setVisible(true);
            lblPriceNameError.setToolTipText("Please Enter Some Value In PriceName Box");
            allvalid = false;
        }
        String QtyName = jtfQty.getText().trim();
        if (Validations.isEmpty(QtyName)) {
            message += "Please Enter Some Value In Qty Box\n\n";
            lblQtyNameError.setVisible(true);
            lblQtyNameError.setToolTipText("Please Enter Some Value In QtyName Box");
            allvalid = false;
        }
        Date stockdate = fdpStockDate.getSelectedDate();
        if (stockdate == null) {
            message += "Please Choose Any Stock Date\n\n";
            allvalid = false;
        }

        if (allvalid) {
            ClothStockTO record = new ClothStockTO();
            ClothInfoTO cit = (ClothInfoTO) jcbClothId.getSelectedItem();
            record.setClothid(cit.getClothid());
            record.setPrice(Float.valueOf(PriceName));
            record.setQty(Integer.parseInt(QtyName));
            record.setStockdate(stockdate);
            ClothStockDAO action = new ClothStockDAO();
            if (btnAssigned.getText().contains("Assign")) {
                if (action.insertRecord(record)) {
                    message = "ClothStock is Assigned";
                } else {
                    message = "Insertion Failure" + action.getError_message();
                    allvalid = false;
                }
            } else if (btnAssigned.getText().contains("Update")) {
                record.setStockid(stockid);
                if (action.updateRecord(record)) {
                    message = " ClothStock information is Updated";

                } else {
                    message = "Updation Failure Due To : " + action.getError_message();
                }
                CommonOperations.showInternalFrame(getDesktopPane(), new ViewClothStock());
                dispose();
            } else {
                message = "Invalid Operation";
            }

        }

        if (allvalid) {
            JOptionPane.showMessageDialog(this, message);
        } else {
            JOptionPane.showMessageDialog(this, message, "Some Failure", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAssignedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssigned;
    private controls.FutureDatePanel fdpStockDate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox jcbClothId;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JTextField jtfQty;
    private javax.swing.JLabel lblPriceNameError;
    private javax.swing.JLabel lblQtyNameError;
    // End of variables declaration//GEN-END:variables
}
