/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.adminscreen;

import Operations.CommonOperations;
import Operations.Validations;
import java.util.List;
import javax.swing.JOptionPane;
import model.To.BrandInfoTO;
import model.To.CategoryInfoTO;
import model.To.ClothInfoTO;
import model.To.SubCategoryTO;
import model.dao.BrandInfoDAO;
import model.dao.CategoryInfoDAO;
import model.dao.ClothInfoDAO;
import model.dao.SubCategoryDAO;

/**
 *
 * @author Rahul khurana
 */
public class AddClothInfo extends javax.swing.JInternalFrame {

    private int clothid;

    public AddClothInfo() {
        initComponents();
        jcbBrandId.removeAllItems();
        jcbBrandId.addItem("Select Any Brand");
        List<BrandInfoTO> brandId = new BrandInfoDAO().getAllRecord();
        if (brandId != null && brandId.size() > 0) {
            for (BrandInfoTO bid : brandId) {
                jcbBrandId.addItem(bid);
            }
        }
        jcbSubCategoryId.removeAllItems();
        jcbSubCategoryId.addItem("Select Any SubCategory");
        List<SubCategoryTO> subcategory = new SubCategoryDAO().getAllRecord();
        if (subcategory != null && subcategory.size() > 0) {
            for (SubCategoryTO sct : subcategory) {
                jcbSubCategoryId.addItem(sct);
            }
        }
        lblPriceNameError.setVisible(false);
        lblDiscountNameError.setVisible(false);
        lblDescriptionNameError.setVisible(false);

    }

    public AddClothInfo(int clothid) {
        this();
        ClothInfoTO record = new ClothInfoDAO().getRecord(clothid);
        if (record != null) {
            this.clothid = clothid;
            setTitle("Update ClothInfo");
            btnAssign.setText("Update SubCategory Details");

            for (int i = 1; i < jcbBrandId.getItemCount(); i++) {
                BrandInfoTO bit = (BrandInfoTO) jcbBrandId.getItemAt(i);
                if (bit.getBrandid() == (record.getBrandid())) {
                    jcbBrandId.setSelectedIndex(i);
                    break;
                }
            }
            for (int i = 1; i < jcbSubCategoryId.getItemCount(); i++) {
                SubCategoryTO sct = (SubCategoryTO) jcbSubCategoryId.getItemAt(i);
                if (sct.getSubcategoryid() == (record.getSubcategoryid())) {
                    jcbSubCategoryId.setSelectedIndex(i);
                    break;
                }
            }
            jtfPrice.setText(String.valueOf(record.getPrice()));
            jtfDiscount.setText(String.valueOf(record.getDiscount()));
            jtfDescription.setText(record.getdescription());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jcbSubCategoryId = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jcbBrandId = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jtfDiscount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfDescription = new javax.swing.JTextField();
        jtfPrice = new javax.swing.JTextField();
        btnAssign = new javax.swing.JButton();
        lblPriceNameError = new javax.swing.JLabel();
        lblDiscountNameError = new javax.swing.JLabel();
        lblDescriptionNameError = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Cloth Info");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setText("Choose Brand Id :-");

        jcbSubCategoryId.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jcbSubCategoryId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbSubCategoryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSubCategoryIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setText("Choose SubCategory Id :-");

        jcbBrandId.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jcbBrandId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbBrandId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBrandIdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("Some Description :-");

        jtfDiscount.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jtfDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDiscountActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel4.setText("Enter Discount :-");

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel5.setText("Enter Price :-");

        jtfDescription.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jtfDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDescriptionActionPerformed(evt);
            }
        });

        jtfPrice.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jtfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPriceActionPerformed(evt);
            }
        });

        btnAssign.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        btnAssign.setText("Assign Cloth Info");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        lblPriceNameError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Error.png"))); // NOI18N

        lblDiscountNameError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Error.png"))); // NOI18N

        lblDescriptionNameError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Error.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfDiscount, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPrice)
                            .addComponent(jtfDescription))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPriceNameError)
                            .addComponent(lblDescriptionNameError)
                            .addComponent(lblDiscountNameError, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcbSubCategoryId, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbBrandId, javax.swing.GroupLayout.Alignment.LEADING, 0, 432, Short.MAX_VALUE))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbBrandId, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSubCategoryId, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPriceNameError)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblDiscountNameError)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblDescriptionNameError)))
                .addGap(18, 18, 18)
                .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbSubCategoryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSubCategoryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSubCategoryIdActionPerformed

    private void jcbBrandIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBrandIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBrandIdActionPerformed

    private void jtfDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDiscountActionPerformed

    private void jtfDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDescriptionActionPerformed

    private void jtfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPriceActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        String message = "";
        boolean allvalid = true;
        if (jcbBrandId.getSelectedIndex() == 0) {
            message += "Please Chosse Any Category\n\n ";
            allvalid = false;
        }
        if (jcbSubCategoryId.getSelectedIndex() == 0) {
            message += "Please Chosse Any Category\n\n ";
            allvalid = false;
        }

        String PriceName = jtfPrice.getText().trim();
        if (Validations.isEmpty(PriceName)) {
            message += "Please Enter Some Value In Price Box\n\n";
            lblPriceNameError.setVisible(true);
            lblPriceNameError.setToolTipText("Please Enter Some Value In PriceName Box");
            allvalid = false;
        }

        

        String DiscountName = jtfDiscount.getText().trim();
        if (Validations.isEmpty(DiscountName)) {
            message += "Please Enter Some Value In Discount Box\n\n";
            lblDiscountNameError.setVisible(true);
            lblDiscountNameError.setToolTipText("Please Enter Some Value In DiscountName Box");
            allvalid = false;
        }
        String DescriptionName = jtfDescription.getText().trim();
        if (Validations.isEmpty(DescriptionName)) {
            message += "Please Enter Some Value In Description Box\n\n";
            lblDescriptionNameError.setVisible(true);
            lblDescriptionNameError.setToolTipText("Please Enter Some Value In Description Name Box");
            allvalid = false;
        }
        if (allvalid) {
            ClothInfoTO record = new ClothInfoTO();
            SubCategoryTO sct = (SubCategoryTO) jcbSubCategoryId.getSelectedItem();
            record.setSubcategoryid(sct.getSubcategoryid());
            BrandInfoTO bit = (BrandInfoTO) jcbBrandId.getSelectedItem();
            record.setBrandid(bit.getBrandid());
            record.setPrice(Float.valueOf(PriceName));
            record.setDiscount(Float.valueOf(DiscountName));
            record.setdescription(DescriptionName);
            ClothInfoDAO action = new ClothInfoDAO();
            if (btnAssign.getText().contains("Assign")) {
                if (action.insertRecord(record)) {
                    message = "ClothInfo is Assigned";
                } else {
                    message = "Insertion Failure" + action.getError_message();
                    allvalid = false;
                }
            } else if (btnAssign.getText().contains("Update")) {
                record.setClothid(clothid);
                if (action.updateRecord(record)) {
                    message = " ClothInfo is Updation";

                } else {
                    message = "Updation Failure Due To : " + action.getError_message();
                }
                CommonOperations.showInternalFrame(getDesktopPane(), new ViewClothInfo());
                dispose();
            } else {
                message = "Invalid Operation";
            }

        }

        if (allvalid) {
            JOptionPane.showMessageDialog(this, message);
        } else {
            JOptionPane.showMessageDialog(this, message, "Some Failure", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox jcbBrandId;
    private javax.swing.JComboBox jcbSubCategoryId;
    private javax.swing.JTextField jtfDescription;
    private javax.swing.JTextField jtfDiscount;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JLabel lblDescriptionNameError;
    private javax.swing.JLabel lblDiscountNameError;
    private javax.swing.JLabel lblPriceNameError;
    // End of variables declaration//GEN-END:variables
}
