/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.adminscreen;

import Operations.CommonOperations;
import Operations.Validations;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.To.CategoryInfoTO;
import model.dao.CategoryInfoDAO;

/**
 *
 * @author Rahul khurana
 */
public class AddNewCategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddNewCategory
     */
    public AddNewCategory() {
        initComponents();

    }

    public AddNewCategory(CategoryInfoTO record) {
        this();
        if (record != null) {
            setTitle("Update Category Details");
            btnSave.setText("Update Category Details");
            jtfCategoryID.setText(record.getCategoryid());
            jtfCategoryName.setText(record.getCategoryname());
            jtfCategoryID.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfCategoryName = new javax.swing.JTextField();
        jtfCategoryID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add New Category");

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("Enter Category ID :");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setText("Enter Category Name :");

        jtfCategoryName.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jtfCategoryID.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        btnSave.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        btnSave.setText("Add Category Details");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfCategoryID, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(jtfCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCategoryID, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfCategoryName, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String message = "";
        String categoryid = jtfCategoryID.getText().trim();
        String categoryname = jtfCategoryName.getText().trim();
        if (Validations.isEmpty(categoryid) || Validations.isEmpty(categoryname)) {
            message = "Please fill all boxes";
        } else {
            CategoryInfoTO record = new CategoryInfoTO();
            record.setCategoryid(categoryid);
            record.setCategoryname(categoryname);
            CategoryInfoDAO action = new CategoryInfoDAO();
            if (btnSave.getText().contains("Add")) {
                if (action.insertRecord(record)) {
                    message = " Category information is saved in information ";
                    bonus_action();
                } else {
                    message = "Insertion Failure Due To : " + action.getError_message();
                    if (message.contains("PRIMARY")) {
                        message = "Category ID is Already Available in System Database. So Try with Different Name";
                    }
                }} else if (btnSave.getText().contains("Update")) {
                if (action.updateRecord(record)) {
                    message = " Category information is Updated";
                    bonus_action();
                } else {
                    message = "Updation Failure Due To : " + action.getError_message();
                }
                CommonOperations.showInternalFrame(getDesktopPane(), new ViewCategory());
                dispose();
            } else {
                message = "Invalid Operation";
            }
        }

        JOptionPane.showMessageDialog(this, message);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void bonus_action() {
        JInternalFrame[] all_frames = getDesktopPane().getAllFrames();
        if (all_frames != null && all_frames.length > 0) {
            for (JInternalFrame jif : all_frames) {
                if (jif instanceof ViewCategory) {
                    ViewCategory vc = (ViewCategory) jif;
                    vc.bindTableDetails();
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfCategoryID;
    private javax.swing.JTextField jtfCategoryName;
    // End of variables declaration//GEN-END:variables
}
