/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.adminscreen;

import Operations.CommonOperations;
import Operations.Validations;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.To.BrandInfoTO;
import model.dao.BrandInfoDAO;

public class AddNewBrand extends javax.swing.JInternalFrame {

    /**
     * Creates new form AssignNewBrand
     */
    public AddNewBrand() {
        initComponents();
        getRootPane().setDefaultButton(btnSave);

    }

    public AddNewBrand(BrandInfoTO record) {
        this();
        if (record != null) {
            setTitle("Update Brand Deatils");
            btnSave.setText("Update Brand Deatils");
            jtfBrandID.setText(record.getBrandid());
            jtfBrandName.setText(record.getBrandname());
            jtfBrandID.setEditable(false);
        }
    }

    @SuppressWarnings("unchecked")

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfBrandID = new javax.swing.JTextField();
        jtfBrandName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Brand Details");

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("Enter Brand ID :");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setText("Enter Brand Name :");

        jtfBrandID.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jtfBrandName.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        btnSave.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        btnSave.setText("Add Brand Details");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfBrandID, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(jtfBrandName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBrandID, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String message = "";
        String brandid = jtfBrandID.getText().trim();
        String brandname = jtfBrandName.getText().trim();
        if (Validations.isEmpty(brandid) || Validations.isEmpty(brandname)) {
            message = "Please fill all boxes";
        } else {
            BrandInfoTO record = new BrandInfoTO();
            record.setBrandid(brandid);
            record.setBrandname(brandname);

            BrandInfoDAO action = new BrandInfoDAO();
            if (btnSave.getText().contains("Add")) {

                if (action.insertRecord(record)) {
                    message = " Brand information is saved in information ";
                    bonus_action();
                } else {
                    message = "Insertion Failure Due To : " + action.getError_message();
                }
            } else if (btnSave.getText().contains("Update")) {
                if (action.updateRecord(record)) {
                    message = " Brand information is Updated";
                    bonus_action();
                } else {
                    message = "Updation Failure Due To : " + action.getError_message();
                }
                CommonOperations.showInternalFrame(getDesktopPane(), new ViewBrand());
                dispose();
            } else {
                message = "Invalid Operation";
            }
        }

        JOptionPane.showMessageDialog(this, message);

    }//GEN-LAST:event_btnSaveActionPerformed
    private void bonus_action() {
        JInternalFrame[] all_frames = getDesktopPane().getAllFrames();
        if (all_frames != null && all_frames.length > 0) {
            for (JInternalFrame jif : all_frames) {
                if (jif instanceof ViewCategory) {
                    ViewBrand vab = (ViewBrand) jif;
                    vab.bindTableDetails();
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtfBrandID;
    private javax.swing.JTextField jtfBrandName;
    // End of variables declaration//GEN-END:variables
}
