/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.adminscreen;

import Operations.CommonOperations;
import java.util.List;
import javax.swing.ImageIcon;
import model.To.CategoryInfoTO;
import model.To.SubCategoryTO;
import model.dao.CategoryInfoDAO;

/**
 *
 * @author Rahul khurana
 */
public class AdminMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainScreen
     */
    public AdminMainScreen() {
        try {
            ImageIcon icon;
            icon = new ImageIcon(getClass().getResource("/photos/cloths.png"));
            setIconImage(icon.getImage());
        } catch (Exception ex) {
        }
        initComponents();
        setSize(1200, 650);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskpane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuCategory = new javax.swing.JMenu();
        jmiAddNewCategory = new javax.swing.JMenuItem();
        jmiViewCategory = new javax.swing.JMenuItem();
        menuSubCategory = new javax.swing.JMenu();
        jmiAddNewSubcategory = new javax.swing.JMenuItem();
        jmiViewSubCategory = new javax.swing.JMenuItem();
        menuBrandInfo = new javax.swing.JMenu();
        jmiAddNewBrand = new javax.swing.JMenuItem();
        jmiViewAssignedBrands = new javax.swing.JMenuItem();
        menuCothInfo = new javax.swing.JMenu();
        jmiAddClothInfo = new javax.swing.JMenuItem();
        jmiViewClothInfo = new javax.swing.JMenuItem();
        menuClothStock = new javax.swing.JMenu();
        jmiAddClothStock = new javax.swing.JMenuItem();
        jmiViewClothStock = new javax.swing.JMenuItem();
        menuBillDetails = new javax.swing.JMenu();
        jmiAddBillDetails = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deskpane.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        javax.swing.GroupLayout deskpaneLayout = new javax.swing.GroupLayout(deskpane);
        deskpane.setLayout(deskpaneLayout);
        deskpaneLayout.setHorizontalGroup(
            deskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1428, Short.MAX_VALUE)
        );
        deskpaneLayout.setVerticalGroup(
            deskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        menuCategory.setText("CategoryInfo");
        menuCategory.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        jmiAddNewCategory.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiAddNewCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Add.png"))); // NOI18N
        jmiAddNewCategory.setText("Add New Category");
        jmiAddNewCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewCategoryActionPerformed(evt);
            }
        });
        menuCategory.add(jmiAddNewCategory);

        jmiViewCategory.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiViewCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Show.png"))); // NOI18N
        jmiViewCategory.setText("View New Category");
        jmiViewCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewCategoryActionPerformed(evt);
            }
        });
        menuCategory.add(jmiViewCategory);

        jMenuBar1.add(menuCategory);

        menuSubCategory.setText("SubCategoryInfo");
        menuSubCategory.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        jmiAddNewSubcategory.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiAddNewSubcategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Add.png"))); // NOI18N
        jmiAddNewSubcategory.setText("Add New SubCategory");
        jmiAddNewSubcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewSubcategoryActionPerformed(evt);
            }
        });
        menuSubCategory.add(jmiAddNewSubcategory);

        jmiViewSubCategory.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiViewSubCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Show.png"))); // NOI18N
        jmiViewSubCategory.setText("View New SubCategory");
        jmiViewSubCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewSubCategoryActionPerformed(evt);
            }
        });
        menuSubCategory.add(jmiViewSubCategory);

        jMenuBar1.add(menuSubCategory);

        menuBrandInfo.setText("BrandInfo");
        menuBrandInfo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        jmiAddNewBrand.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiAddNewBrand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Add.png"))); // NOI18N
        jmiAddNewBrand.setText("Add New Brand");
        jmiAddNewBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewBrandActionPerformed(evt);
            }
        });
        menuBrandInfo.add(jmiAddNewBrand);

        jmiViewAssignedBrands.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiViewAssignedBrands.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Show.png"))); // NOI18N
        jmiViewAssignedBrands.setText("View New Brand");
        jmiViewAssignedBrands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewAssignedBrandsActionPerformed(evt);
            }
        });
        menuBrandInfo.add(jmiViewAssignedBrands);

        jMenuBar1.add(menuBrandInfo);

        menuCothInfo.setText("ClothInfo");
        menuCothInfo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        jmiAddClothInfo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiAddClothInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Add.png"))); // NOI18N
        jmiAddClothInfo.setText("Add Cloth Info ");
        jmiAddClothInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddClothInfoActionPerformed(evt);
            }
        });
        menuCothInfo.add(jmiAddClothInfo);

        jmiViewClothInfo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiViewClothInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Show.png"))); // NOI18N
        jmiViewClothInfo.setText("View Cloth Info");
        jmiViewClothInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewClothInfoActionPerformed(evt);
            }
        });
        menuCothInfo.add(jmiViewClothInfo);

        jMenuBar1.add(menuCothInfo);

        menuClothStock.setText("ClothStock");
        menuClothStock.setFocusable(false);
        menuClothStock.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        jmiAddClothStock.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiAddClothStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Add.png"))); // NOI18N
        jmiAddClothStock.setText("Add Cloth Stock");
        jmiAddClothStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddClothStockActionPerformed(evt);
            }
        });
        menuClothStock.add(jmiAddClothStock);

        jmiViewClothStock.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiViewClothStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Show.png"))); // NOI18N
        jmiViewClothStock.setText("View Cloth Stock");
        jmiViewClothStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewClothStockActionPerformed(evt);
            }
        });
        menuClothStock.add(jmiViewClothStock);

        jMenuBar1.add(menuClothStock);

        menuBillDetails.setText("BillDetails");
        menuBillDetails.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        jmiAddBillDetails.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiAddBillDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Add.png"))); // NOI18N
        jmiAddBillDetails.setText("Generate Bill");
        jmiAddBillDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddBillDetailsActionPerformed(evt);
            }
        });
        menuBillDetails.add(jmiAddBillDetails);

        jMenuBar1.add(menuBillDetails);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(deskpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskpane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiViewClothStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewClothStockActionPerformed
        CommonOperations.showInternalFrame(deskpane, new ViewClothStock());
    }//GEN-LAST:event_jmiViewClothStockActionPerformed

    private void jmiAddClothStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddClothStockActionPerformed
        AddClothStock acs = new AddClothStock();
        deskpane.add(acs);
        acs.setVisible(true);
    }//GEN-LAST:event_jmiAddClothStockActionPerformed

    private void jmiViewClothInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewClothInfoActionPerformed
        CommonOperations.showInternalFrame(deskpane, new ViewClothInfo());
    }//GEN-LAST:event_jmiViewClothInfoActionPerformed

    private void jmiAddClothInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddClothInfoActionPerformed
        AddClothInfo aci = new AddClothInfo();
        deskpane.add(aci);
        aci.setVisible(true);
    }//GEN-LAST:event_jmiAddClothInfoActionPerformed

    private void jmiViewAssignedBrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewAssignedBrandsActionPerformed
        CommonOperations.showInternalFrame(deskpane, new ViewBrand());
    }//GEN-LAST:event_jmiViewAssignedBrandsActionPerformed

    private void jmiAddNewBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewBrandActionPerformed
        AddNewBrand anb = new AddNewBrand();
        deskpane.add(anb);
        anb.setVisible(true);
    }//GEN-LAST:event_jmiAddNewBrandActionPerformed

    private void jmiViewSubCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewSubCategoryActionPerformed
        CommonOperations.showInternalFrame(deskpane, new ViewSubCategory());
    }//GEN-LAST:event_jmiViewSubCategoryActionPerformed

    private void jmiAddNewSubcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewSubcategoryActionPerformed
        AddSubCategory asc = new AddSubCategory();
        deskpane.add(asc);
        asc.setVisible(true);
    }//GEN-LAST:event_jmiAddNewSubcategoryActionPerformed

    private void jmiViewCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewCategoryActionPerformed
        ViewCategory vc = new ViewCategory();
        deskpane.add(vc);
        vc.setVisible(true);

    }//GEN-LAST:event_jmiViewCategoryActionPerformed

    private void jmiAddNewCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewCategoryActionPerformed
        AddNewCategory anc = new AddNewCategory();
        deskpane.add(anc);
        anc.setVisible(true);
    }//GEN-LAST:event_jmiAddNewCategoryActionPerformed

    private void jmiAddBillDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddBillDetailsActionPerformed
        BillDetails bd = new BillDetails();
        deskpane.add(bd);
        bd.setVisible(true);

    }//GEN-LAST:event_jmiAddBillDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskpane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAddBillDetails;
    private javax.swing.JMenuItem jmiAddClothInfo;
    private javax.swing.JMenuItem jmiAddClothStock;
    private javax.swing.JMenuItem jmiAddNewBrand;
    private javax.swing.JMenuItem jmiAddNewCategory;
    private javax.swing.JMenuItem jmiAddNewSubcategory;
    private javax.swing.JMenuItem jmiViewAssignedBrands;
    private javax.swing.JMenuItem jmiViewCategory;
    private javax.swing.JMenuItem jmiViewClothInfo;
    private javax.swing.JMenuItem jmiViewClothStock;
    private javax.swing.JMenuItem jmiViewSubCategory;
    private javax.swing.JMenu menuBillDetails;
    private javax.swing.JMenu menuBrandInfo;
    private javax.swing.JMenu menuCategory;
    private javax.swing.JMenu menuClothStock;
    private javax.swing.JMenu menuCothInfo;
    private javax.swing.JMenu menuSubCategory;
    // End of variables declaration//GEN-END:variables

}
