/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.adminscreen;

import Operations.CommonOperations;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.To.ClothInfoTO;
import model.To.SubCategoryTO;
import model.dao.ClothInfoDAO;
import model.dao.SubCategoryDAO;

/**
 *
 * @author Rahul khurana
 */
public class ViewClothInfo extends javax.swing.JInternalFrame {

    List<ClothInfoTO> clothInfo;
    private JPopupMenu popup;
    private int clothid;

    public ViewClothInfo() {
        initComponents();
        bindTableDetails();
        preparePopupMenu();
        clothid = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableClothInfo = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Cloth Info");

        tableClothInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableClothInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClothInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableClothInfo);

        btnRefresh.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnRefresh.setText("Refresh Details");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preparePopupMenu() {
        popup = new JPopupMenu();
        JMenuItem delete_item = new JMenuItem("Delete This Record");
        JMenuItem edit_item = new JMenuItem("Edit This Record");
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/photos/edits.png"));
            edit_item.setIcon(icon);
        } catch (Exception ex) {
        }
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/photos/Delete.png"));
            delete_item.setIcon(icon);
        } catch (Exception ex) {
        }

        popup.add(delete_item);
        popup.add(edit_item);
        delete_item.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                delete_record();
            }
        });
        edit_item.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                edit_record();
            }
        });

    }

    public void delete_record() {
        if (clothid != 0 && clothInfo != null) {
            int result = JOptionPane.showConfirmDialog(this, "Are You Sure To Removed This Record?", "Message From Admin", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                ClothInfoDAO action = new ClothInfoDAO();
                String message = "";
                if (action.deleteRecord(clothid)) {
                    message = "Record is Removed From System Database";
                } else {
                    message = "Deletion Failure Due To : " + action.getError_message();
                    bindTableDetails();
                }
                JOptionPane.showMessageDialog(this, message);
            }

        }
        clothid = 0;

    }

    public void edit_record() {
        if (clothid != -1 && clothInfo != null) {
            CommonOperations.showInternalFrame(getDesktopPane(), new AddClothInfo(clothid));
            dispose();

        }
    }

    private void bindTableDetails() {
        clothInfo = new ClothInfoDAO().getAllRecord();
        String[] col_name = {" Clothid ", " Brand Id ", "SubCategory Id ", "Price ", "Discount", "Description",};
        Object[][] records = null;
        if (clothInfo != null && clothInfo.size() > 0) {
            records = new Object[clothInfo.size()][col_name.length];
            int index = 0;
            for (ClothInfoTO sct : clothInfo) {
                records[index] = new Object[]{sct.getClothid(), sct.getBrandid(), sct.getSubcategoryid(), sct.getPrice(), sct.getDiscount(), sct.getdescription()};
                index++;
            }
        } else {
            records = new Object[1][col_name.length];
            records[0] = new Object[]{"No Record ", "No Record ", "No Record", "No Record ", "No Record", "No Record "};
        }
        DefaultTableModel model
                = new DefaultTableModel(records, col_name) {

                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };
        tableClothInfo.setModel(model);

    }

    private void tableClothInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClothInfoMouseClicked

        /*if (evt.getButton() == MouseEvent.BUTTON3) {
         //System.out.println("Right Clicked");
         int row_point = tableClothInfo.rowAtPoint(evt.getPoint());
         tableClothInfo.getSelectionModel().setSelectionInterval(row_point, row_point);
         popup.show(tableClothInfo, evt.getX(), evt.getY());
         //System.out.println(tableCategory.getSelectedRow());
         clothid = tableClothInfo.getSelectedRow();
         }*/
        if (SwingUtilities.isRightMouseButton(evt)) {
            int row_point = tableClothInfo.rowAtPoint(evt.getPoint());
            tableClothInfo.getSelectionModel().setSelectionInterval(row_point, row_point);
            popup.show(tableClothInfo, evt.getX(), evt.getY());
            int row = tableClothInfo.getSelectedRow();
            clothid = Integer.parseInt(tableClothInfo.getValueAt(row, 0).toString());
        }
    }//GEN-LAST:event_tableClothInfoMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bindTableDetails();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableClothInfo;
    // End of variables declaration//GEN-END:variables
}
