/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.adminscreen;

import Operations.CommonOperations;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultTreeModel;
import model.To.CategoryInfoTO;
import model.dao.CategoryInfoDAO;

/**
 *
 * @author Rahul khurana
 */
public class ViewCategory extends javax.swing.JInternalFrame {

    private List<CategoryInfoTO> category;
    private JPopupMenu popup;
    private int srow;

    public ViewCategory() {
        initComponents();
        bindTableDetails();
        preparePopupMenu();
        srow = -1;
    }

    private void preparePopupMenu() {
        popup = new JPopupMenu();
        JMenuItem delete_item = new JMenuItem("Delete This Record");
        JMenuItem edit_item = new JMenuItem("Edit This Record");
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/photos/edits.png"));
            edit_item.setIcon(icon);
        } catch (Exception ex) {
        }
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/photos/Delete.png"));
            delete_item.setIcon(icon);
        } catch (Exception ex) {
        }

        popup.add(delete_item);
        popup.add(edit_item);
        delete_item.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                delete_record();
            }
        });
        edit_item.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                edit_record();
            }
        });
    }

    public void delete_record() {
        if (srow != -1 && category != null && srow < category.size()) {
            CategoryInfoTO record = category.get(srow);
            if (record != null) {
                int result = JOptionPane.showConfirmDialog(this, "Are You Sure To Removed This Record?", "Message From Admin", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    CategoryInfoDAO action = new CategoryInfoDAO();
                    String message = "";
                    if (action.deleteRecord(record.getCategoryid())) {
                        message = "Record is Removed From System Database";
                    } else {
                        message = "Deletion Failure Due To : " + action.getError_message();
                        if(message.contains("FOREIGN")){
                            message = "This word is associated  with other record. So can Not be deleted";
                        }
                        bindTableDetails();
                    }
                    JOptionPane.showMessageDialog(this, message);
                }
            }
        }
        srow = -1;
    }

    public void edit_record() {
        if (srow != -1 && category != null && srow < category.size()) {
            CategoryInfoTO record = category.get(srow);
            if (record != null) {
                CommonOperations.showInternalFrame(getDesktopPane(), new AddNewCategory(record));
                dispose();
            }
        }
        srow = -1;
    }

    public void bindTableDetails() {
        category = new CategoryInfoDAO().getAllRecord();
        String[] col_name = {"Category Id ", "Category Name"};
        Object[][] records = null;
        if (category != null && category.size() > 0) {
            records = new Object[category.size()][col_name.length];
            int index = 0;
            for (CategoryInfoTO ct : category) {
                records[index] = new Object[]{ct.getCategoryid(), ct.getCategoryname()};
                index++;
            }
        } else {
            records = new Object[1][col_name.length];
            records[0] = new Object[]{"No Record ", "No Record"};
        }
        DefaultTableModel model
                = new DefaultTableModel(records, col_name) {

                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }

                };
        tableCategory.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategory = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Category");
        setToolTipText("");

        tableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCategory);

        btnRefresh.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnRefresh.setText("Refresh Details");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bindTableDetails();


    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tableCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoryMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            //System.out.println("Right Clicked");
            int row_point = tableCategory.rowAtPoint(evt.getPoint());
            tableCategory.getSelectionModel().setSelectionInterval(row_point, row_point);
            popup.show(tableCategory, evt.getX(), evt.getY());
            //System.out.println(tableCategory.getSelectedRow());
            srow = tableCategory.getSelectedRow();
        }
    }//GEN-LAST:event_tableCategoryMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCategory;
    // End of variables declaration//GEN-END:variables

}
