/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.adminscreen;

import Operations.CommonOperations;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.To.ClothInfoTO;
import model.To.ClothStockTO;
import model.To.SubCategoryTO;
import model.dao.ClothInfoDAO;
import model.dao.ClothStockDAO;
import model.dao.SubCategoryDAO;

/**
 *
 * @author Rahul khurana
 */
public class ViewClothStock extends javax.swing.JInternalFrame {

    List<ClothStockTO> clothstock;
    private JPopupMenu popup;
    private int stockid;
    
    public ViewClothStock() {
        initComponents();
        bindTableDetails();
        preparePopupMenu();
        stockid = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableClothStock = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Cloth Stock");

        tableClothStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableClothStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClothStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableClothStock);

        btnRefresh.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnRefresh.setText("Refresh Details");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void preparePopupMenu() {
        popup = new JPopupMenu();
        JMenuItem delete_item = new JMenuItem("Delete This Record");
        JMenuItem edit_item = new JMenuItem("Edit This Record");
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/photos/edits.png"));
            edit_item.setIcon(icon);
        } catch (Exception ex) {
        }
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/photos/Delete.png"));
            delete_item.setIcon(icon);
        } catch (Exception ex) {
        }

        popup.add(delete_item);
        popup.add(edit_item);
        delete_item.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                delete_record();
            }
        });
           edit_item.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                edit_record();
            }
        });

        }
        public void delete_record() {
        if (stockid != 0 && clothstock != null) {
                int result = JOptionPane.showConfirmDialog(this, "Are You Sure To Removed This Record?", "Message From Admin", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    ClothStockDAO action = new ClothStockDAO();
                    String message = "";
                    if (action.deleteRecord(stockid)) {
                        message = "Record is Removed From System Database";
                    } else {
                        message = "Deletion Failure Due To : " + action.getError_message();
                        bindTableDetails();
                    }
                    JOptionPane.showMessageDialog(this, message);
                }
            
        }
        stockid = 0;

            
        }
    public void edit_record() {
        if (stockid != -1 && clothstock !=null) {
            CommonOperations.showInternalFrame(getDesktopPane(), new AddClothStock(stockid));
            dispose();
        }
        
        
        /*if (stockid != -1 && clothstock != null && stockid < clothstock.size()) {
            ClothStockTO record = clothstock.get(stockid);
            if (record != null) {
                CommonOperations.showInternalFrame(getDesktopPane(), new AddClothStock(stockid));
                dispose();
            }*/
        

        }

    

    
    
    private void bindTableDetails(){
        clothstock = new ClothStockDAO().getAllRecord();
        String[] col_name = {"Stockid","Cloth Id", "Price","Quantity","Stock Date"};
        Object[][] records = null;
        if (clothstock != null && clothstock.size() > 0) {
            records = new Object[clothstock.size()][col_name.length];
            int index = 0;
            for (ClothStockTO cst : clothstock) {
                records[index] = new Object[]{cst.getStockid(),cst.getClothid(), cst.getPrice(),cst.getQty(),cst.getStockdate()};
                index++;
            }
        } else {
            records = new Object[1][col_name.length];
            records[0] = new Object[]{ "No Record","No Record ", "No Record", "No Record"};
        }
        DefaultTableModel model
                = new DefaultTableModel(records, col_name) {

                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };
        tableClothStock.setModel(model);
    
        }
    private void tableClothStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClothStockMouseClicked
        /*if (evt.getButton() == MouseEvent.BUTTON3) {
            //System.out.println("Right Clicked");
            int row_point = tableClothStock.rowAtPoint(evt.getPoint());
            tableClothStock.getSelectionModel().setSelectionInterval(row_point, row_point);
            popup.show(tableClothStock, evt.getX(), evt.getY());
            //System.out.println(tableCategory.getSelectedRow());
            stockid = tableClothStock.getSelectedRow();
        }*/
        if(SwingUtilities.isRightMouseButton(evt)){
            int row_point = tableClothStock.rowAtPoint(evt.getPoint());
            tableClothStock.getSelectionModel().setSelectionInterval(row_point,row_point);
            popup.show(tableClothStock, evt.getX() , evt.getY());
            int row = tableClothStock.getSelectedRow();
            stockid = Integer.parseInt(tableClothStock.getValueAt(row, 0).toString());
        }
        
    }//GEN-LAST:event_tableClothStockMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bindTableDetails();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableClothStock;
    // End of variables declaration//GEN-END:variables
}
